"""
Infrastructure Cost Distribution Pie Chart
Professional pie chart using gs_plot_helpers styling with full feature set
"""

import matplotlib.pyplot as plt
import pandas as pd
import os
import sys

# Add parent directories to path to find plot_buddy
current_dir = os.path.dirname(os.path.abspath(__file__))
utils_dir = os.path.join(current_dir, '../../utils')
sys.path.insert(0, utils_dir)
from plot_buddy import PlotBuddy

CHART_DATA = {
    'capex_breakdown': {
        'categories': ['Gas Turbines', 'Datacenter Shell', 'Compute Servers'],
        'percentages': [6, 29, 65],
        'descriptions': [
            'Gas turbine power generation',
            'Datacenter infrastructure and cooling', 
            'Server hardware and compute resources'
        ]
    },
    'nvidia_breakdown': {
        'categories': ['NVIDIA Revenue', 'NVIDIA Margin', 'Other Compute Servers'],
        'percentages': [40, 25, 35], # Example percentages, adjust as needed
        'descriptions': [
            'Revenue generated by NVIDIA GPUs',
            'Profit margin from NVIDIA GPU sales',
            'Other compute server components and vendors'
        ]
    }
}

def prepare_gpu_data(chart_key):
    """
    Prepare infrastructure distribution data
    """
    data = {
        'Category': CHART_DATA[chart_key]['categories'],
        'Percentage': CHART_DATA[chart_key]['percentages'],
        'Description': CHART_DATA[chart_key]['descriptions']
    }
    return pd.DataFrame(data)

def create_gpu_pie_chart(data, save_path=None, title=None, subtitle=None):
    """Create a professional pie chart with 6%, 29%, 65% distribution"""
    
    # Initialize PlotBuddy with style directory
    buddy = PlotBuddy(style_dir_path=os.path.join(os.path.dirname(__file__), '../../utils/styles'))
    
    with buddy.get_style_context('gs'):
        fig, ax = buddy.setup_figure()
        
        # Get colors from current matplotlib color cycle (defined in gs.mplstyle)
        colors = plt.rcParams['axes.prop_cycle'].by_key()['color'][:len(data)]
        
        # Create pie chart without labels (legend will handle them)
        wedges, texts, autotexts = ax.pie(data['Percentage'], 
                                         labels=None,  # Remove labels from pie chart
                                         colors=colors,
                                         autopct='%1.0f%%', 
                                         startangle=90,
                                         explode=(0.05, 0.05, 0.1))  # Slightly separate slices
        
        # Style the percentage text
        for autotext in autotexts:
            autotext.set_color('white')
            autotext.set_fontweight('bold')
            autotext.set_fontsize(16)
        
        # Equal aspect ratio ensures that pie is drawn as a circle
        ax.axis('equal')
        
        # Add titles using PlotBuddy
        buddy.add_titles(ax, 
                        title=title,
                        subtitle=subtitle)
        
        # Create legend entries for the GS helper function
        # Add invisible plot elements to create legend handles
        for i, (category, percentage) in enumerate(zip(data['Category'], data['Percentage'])):
            ax.plot([], [], 's', color=colors[i], markersize=10, 
                   label=f"{category}: {percentage}%")
        
        # Use GS helper function for professional legend positioning
        buddy.create_legend(ax, ncol=3)
        
        # Add logo and source using PlotBuddy
        logo_path = os.path.join(os.path.dirname(__file__), '../../../logos', 'gs_logo.png')
        try:
            buddy.add_logo(fig, logo_path)
        except FileNotFoundError:
            print("Warning: GS logo not found, continuing without logo")
        
        buddy.add_source_citation(fig, "Industry Estimates")
        
        # Apply layout using PlotBuddy
        buddy.apply_tight_layout(fig)
        
        # Save chart
        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches='tight')
        
        return fig, ax

def generate_gpu_pie_chart(display=True):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # Generate Capex Breakdown Pie Chart
    data_capex = prepare_gpu_data('capex_breakdown')
    save_path_capex = os.path.join(script_dir, 'infrastructure_cost_pie_chart.png')
    create_gpu_pie_chart(data_capex, save_path_capex, 
                         title="AI Infrastructure Capex Breakdown",
                         subtitle="GPU servers dominate overall cost and maximizing their utilization is the dominant consideration.")
    
    # Generate NVIDIA Breakdown Pie Chart
    data_nvidia = prepare_gpu_data('nvidia_breakdown')
    save_path_nvidia = os.path.join(script_dir, 'nvidia_breakdown_pie_chart.png')
    create_gpu_pie_chart(data_nvidia, save_path_nvidia, 
                         title="NVIDIA's Share of Compute Server Revenue and Margin",
                         subtitle="A closer look at NVIDIA's contribution within the compute server segment.")
    
    if display:
        plt.show()


# Example usage
if __name__ == "__main__":
    import sys
    
    # Check for --no-display flag
    display = '--no-display' not in sys.argv
    
    # Generate the pie chart
    result = generate_gpu_pie_chart(display=display)
    
    print("Infrastructure Cost Distribution Pie Chart generated successfully!")
    print("Files saved in current directory:")
    print("  - infrastructure_cost_pie_chart.png (Capex Breakdown Pie Chart)")
    print("  - nvidia_breakdown_pie_chart.png (NVIDIA Breakdown Pie Chart)")
    print("  - nvidia_breakdown_pie_chart.png (NVIDIA Breakdown Pie Chart)")